name: PHP CI

on: [push]

jobs:
    build-test:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                include:
                    - { php-version: '7.3', orm-version: '2.7' }
                    - { php-version: '7.4', orm-version: '2.7' }
                    - { php-version: '8.0', orm-version: '2.7' }
                    - { php-version: '8.1', orm-version: '2.7' }
                    - { php-version: '8.2', orm-version: '2.7' }
                    - { php-version: '8.3', orm-version: '2.7' }

                    - { php-version: '8.1', orm-version: '3.0' }
                    - { php-version: '8.2', orm-version: '3.0' }
                    - { php-version: '8.3', orm-version: '3.0' }

        name: PHP ${{ matrix.php-version }} / ORM ${{ matrix.orm-version }}
        steps:
            - uses: actions/checkout@v2

            - uses: shivammathur/setup-php@v2
              with:
                  php-version: "${{ matrix.php-version }}"
                  extensions: gd, zip, mongodb

            - run: composer validate

            - id: composer-cache
              run: echo "::set-output name=dir::$(composer config cache-files-dir)"

            - uses: actions/cache@v1
              with:
                  path: ${{ steps.composer-cache.outputs.dir }}
                  key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                  restore-keys: ${{ runner.os }}-composer-

            - run: composer require --dev "doctrine/orm:^${{ matrix.orm-version }}" --no-update

            - run: composer install

            - run: vendor/bin/phpunit
